# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0004_auto_20180701_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='streetNoW',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workBlock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workBuild',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_country', related_query_name='work_country', to='worksheet.Country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workCounty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_state', related_query_name='work_state', to='worksheet.State'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workStreet',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='workZip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
