# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0014_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='ID_depto',
            new_name='ID_ciudad',
        ),
    ]
