# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0016_auto_20180727_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilstatus',
            name='name',
        ),
        migrations.AlterField(
            model_name='civilstatus',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
