# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0020_equipotrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausentismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('motivo', models.TextField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('aprobado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='au_emp', related_query_name='au_emp', to='worksheet.Employee')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.Employee')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='au_usermod', related_query_name='au_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
