# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0024_motivosdespido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivosdespido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
