# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0027_claseeducacion_educacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('grupo_salarial', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.Employee')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eV_gerente', related_query_name='eV_gerente', to='worksheet.Employee')),
            ],
        ),
    ]
