# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0031_empleosanteriores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('bic_swift', models.CharField(blank=True, max_length=100, null=True)),
                ('of_postal', models.BooleanField()),
                ('cuenta_bancaria', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.Country')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoComisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grpcom_usermod', related_query_name='grpcom_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('porcentaje_comision', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('tel_movil', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=150)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.Employee')),
                ('grupo_comisiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.GrupoComisiones')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_usermod', related_query_name='vendedor_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
