# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0033_auto_20180820_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocomisiones',
            name='date_mod',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
