# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0034_grupocomisiones_date_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocomisiones',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
