# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0039_empleoanterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleoanterior',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='EmpleoAnterior',
        ),
    ]
