# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0040_auto_20180823_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extEmpNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
