# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0044_usuarioempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='worksheet.Empresa'),
            preserve_default=False,
        ),
    ]
