# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0046_empresa_grupo_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='grupo_fk',
        ),
    ]
