# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0047_remove_empresa_grupo_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.Group'),
        ),
    ]
