# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0050_bank_sucursal_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pos_empreg', related_query_name='pos_empreg', to='worksheet.Empresa'),
        ),
    ]
