# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0051_position_empresa_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dep_empreg', related_query_name='dep_empreg', to='worksheet.Empresa'),
        ),
    ]
