# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0056_position_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
    ]
