# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0057_remove_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
