# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0066_auto_20181121_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='termreason',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
