# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-21 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0068_auto_20181121_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sex',
            name='code',
        ),
    ]
