# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-21 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0074_costunit_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costunit',
            old_name='codigo',
            new_name='code',
        ),
    ]
