# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-22 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0075_auto_20181121_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='sucursal_reg',
        ),
    ]
