# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0077_auto_20181122_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
