# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-22 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0079_civilstatus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empl_empreg', related_query_name='empl_empreg', to='worksheet.Empresa'),
        ),
    ]
