# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-23 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0086_auto_20181123_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionestrabajo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='funcionestrabajo',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fun_empreg', related_query_name='fun_empreg', to='worksheet.Empresa'),
        ),
    ]
