# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0089_auto_20181123_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipotrabajo',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
