# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0091_auto_20181123_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='au_empreg', related_query_name='au_empreg', to='worksheet.Empresa'),
        ),
    ]
