# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0094_auto_20181126_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ed_empreg', related_query_name='Ed_empreg', to='worksheet.Empresa'),
        ),
    ]
