# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0097_auto_20181126_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleosanteriores',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='empAnt_empreg', related_query_name='empAnt_empreg', to='worksheet.Empresa'),
        ),
    ]
