# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0104_auto_20181127_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='state_pais', related_query_name='state_pais', to='worksheet.Country'),
        ),
    ]
