# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0105_auto_20181127_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='empleado',
        ),
    ]
