# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0109_employee_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryunit',
            name='dias_salario',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
