# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0111_remove_salaryunit_dias_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryunit',
            name='dias_salario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
