# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0114_salaryunit_dias_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/emp_photos')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture',
        ),
        migrations.AddField(
            model_name='imagenempleado',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Employee', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='imagenempleado',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imgemp_empreg', related_query_name='imgemp_empreg', to='worksheet.Empresa'),
        ),
        migrations.AddField(
            model_name='imagenempleado',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgemp_usermod', related_query_name='imgemp_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenempleado',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
