# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-07 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0115_auto_20181205_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenempleado',
            name='user_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
