# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-27 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0116_auto_20181207_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementosSalariales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incremento', models.DateField()),
                ('salario_anterior', models.DecimalField(decimal_places=3, max_digits=18)),
                ('incremento', models.DecimalField(decimal_places=3, max_digits=18)),
                ('nuevo_salario', models.DecimalField(decimal_places=3, max_digits=18)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('salario_actual', models.BooleanField(default=True)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Employee', verbose_name='Empleado')),
                ('motivo_aumento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.MotivoAumentoSueldo')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incsal_usermod', related_query_name='incsal_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='imagenempleado',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Employee', verbose_name='Empleado'),
        ),
    ]
