# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0120_auto_20181227_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementossalariales',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa'),
        ),
    ]
