# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-12 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0121_incrementossalariales_empresa_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_g', models.CharField(max_length=50)),
                ('gravable', models.BooleanField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa')),
                ('sucursal_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_i', models.CharField(max_length=50)),
                ('gravable', models.BooleanField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa')),
                ('sucursal_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcon_usermod', related_query_name='tcon_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ting_usermod', related_query_name='ting_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_planilla', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tnom_usermod', related_query_name='tnom_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingresoindividual',
            name='tipo_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoIngreso'),
        ),
        migrations.AddField(
            model_name='ingresoindividual',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingind_usermod', related_query_name='ingind_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresoindividual',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresogeneral',
            name='tipo_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoIngreso', verbose_name='tipo ingreso'),
        ),
        migrations.AddField(
            model_name='ingresogeneral',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingg_usermod', related_query_name='ingg_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresogeneral',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
