# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0123_auto_20190112_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salario_diario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
