# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0125_planilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='correlativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correlativo'),
        ),
    ]
