# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-01 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0127_planilladetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladetalle',
            name='dias_ausentes_con_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planilladetalle',
            name='dias_ausentes_sin_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
