# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0128_auto_20190201_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='sucursal_reg',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Branch'),
            preserve_default=False,
        ),
    ]
