# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-19 20:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0129_ausentismo_sucursal_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_deduccion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('empresa_reg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tded_usermod', related_query_name='tded_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Deduccion',
                'verbose_name_plural': 'Tipo Deducciones',
            },
        ),
    ]
