# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-22 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0132_deducciongeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpuestoSobreRenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hasta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_label', models.CharField(max_length=50)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isv_usermod', related_query_name='isv_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'impuesto sobre renta',
                'verbose_name_plural': 'impuestos sobre rentas',
            },
        ),
    ]
