# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0133_impuestosobrerenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguroSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('techo', models.CharField(max_length=70)),
                ('porcentaje_e', models.CharField(max_length=50)),
                ('valor_e', models.CharField(max_length=50)),
                ('porcentaje_p', models.CharField(max_length=50)),
                ('valor_p', models.CharField(max_length=50)),
                ('total_p', models.CharField(max_length=50)),
                ('total_v', models.CharField(max_length=50)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ss_usermod', related_query_name='ss_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguro Social',
                'verbose_name_plural': 'Seguro Social',
            },
        ),
    ]
