# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-28 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0135_impuestovecinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=50, verbose_name='Jornada')),
                ('horaini', models.TimeField(verbose_name='Hora Inicial')),
                ('horafin', models.TimeField(verbose_name='Hora Fin')),
                ('horasDiarias', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas Diarias')),
                ('horasSemana', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas Semana')),
                ('noExedeNocturno', models.IntegerField()),
                ('horaExtra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hora Extra')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='he_usermod', related_query_name='he_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hora Extra',
                'verbose_name_plural': 'Horas Extras',
            },
        ),
    ]
