# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0137_salariominimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoGlobalDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('fecha_valida', models.DateField(verbose_name='Fecha valida')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.IngresoGeneral', verbose_name='Ingreso General')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla')),
                ('sucursal_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Branch', verbose_name='Sucursal registro')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoContrato', verbose_name='Tipo de Contrato')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.SalaryUnit', verbose_name='Tipo de Pago')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='igd_usermod', related_query_name='igd_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso detalle',
                'verbose_name_plural': 'Ingresos detalles',
            },
        ),
    ]
