# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0138_ingresoglobaldetalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngresoGlobalDetalle',
            new_name='IngresoGeneralDetalle',
        ),
    ]
