# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0145_deduccionindividualplanilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Branch', verbose_name='Empresa registro'),
        ),
    ]
