# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0147_auto_20190325_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='empresa_reg',
        ),
        migrations.AddField(
            model_name='empresa',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo'),
        ),
    ]
