# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0148_auto_20190325_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='code',
        ),
        migrations.RemoveField(
            model_name='grupocorporativo',
            name='empresa_reg',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.GrupoCorporativo'),
        ),
    ]
