# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-26 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0149_auto_20190325_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCorporacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('corporacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.GrupoCorporativo', verbose_name='Grupo Corporativo')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uscorp_usermod', related_query_name='uscorp_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uscorp_user', related_query_name='uscorp_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Corporacion',
                'verbose_name_plural': 'Usuarios Corporaciones',
            },
        ),
        migrations.RemoveField(
            model_name='usuarioempresa',
            name='empresa_reg',
        ),
        migrations.RemoveField(
            model_name='usuariosucursal',
            name='empresa_reg',
        ),
    ]
