# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0150_auto_20190326_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladetalle',
            name='total_deducciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total Egresos'),
        ),
        migrations.AddField(
            model_name='planilladetalle',
            name='total_ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total Ingresos'),
        ),
    ]
