# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0154_auto_20190424_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguroSocialAjuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Porcentaje')),
                ('maximo_dias', models.CharField(max_length=50, verbose_name='Maximo Dias')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'segurosocialajuste',
                'verbose_name_plural': 'segurosocialajustes',
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='grupocorporativo',
            options={'verbose_name': 'Grupo Corporativo', 'verbose_name_plural': 'Grupos Corporativos'},
        ),
        migrations.AlterField(
            model_name='planilladetalleingresos',
            name='ingreso',
            field=models.CharField(max_length=250, verbose_name='Ingreso'),
        ),
        migrations.AddField(
            model_name='segurosocialajuste',
            name='sucursal_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Branch', verbose_name='Sucursal registro'),
        ),
        migrations.AddField(
            model_name='segurosocialajuste',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segsocajus_usermod', related_query_name='segsocajus_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segurosocialajuste',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registro'),
        ),
    ]
