# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0155_auto_20190522_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segurosocialajuste',
            name='sucursal_reg',
        ),
        migrations.AddField(
            model_name='segurosocialajuste',
            name='empresa_reg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa'),
            preserve_default=False,
        ),
    ]
