# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0156_auto_20190522_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladetalle',
            name='comentario',
            field=models.TextField(default='', verbose_name='Comentario'),
            preserve_default=False,
        ),
    ]
