# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0159_empleadodeducciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadodeducciones',
            options={'verbose_name': 'Asignar Deduccion Legal Empleado', 'verbose_name_plural': 'Asignar Deducciones Legales a Empleado'},
        ),
        migrations.AddField(
            model_name='tipodeduccion',
            name='orden',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='empleadodeducciones',
            name='deduccion',
            field=models.CharField(choices=[('IHSS', 'IHSS'), ('RAP', 'RAP'), ('ISR', 'Impuesto Sobre Renta'), ('IMV', 'Impuesto Vecinal')], max_length=50, verbose_name='Deduccion'),
        ),
    ]
