# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0161_auto_20190611_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteSalarioDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Salario')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Employee', verbose_name='Empleado')),
                ('empresa_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limded_usermod', related_query_name='limded_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limite Salario Deduccion',
                'verbose_name_plural': 'Limite Salario Deduccions',
            },
        ),
        migrations.AlterField(
            model_name='empleadodeducciones',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
