# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0162_auto_20190620_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitesalariodeduccion',
            name='empresa_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Empresa'),
        ),
        migrations.AlterField(
            model_name='limitesalariodeduccion',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
