# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0163_auto_20190626_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='funcion_operativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.FuncionesTrabajo', verbose_name='Funcion Operativa'),
        ),
    ]
