# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0164_position_funcion_operativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pager',
        ),
    ]
