# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0166_auto_20190628_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lat',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='employee',
            name='lng',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='socialNetwork1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Red Social 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='socialNetwork2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Red Social 2'),
        ),
    ]
