# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0167_auto_20190628_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rtn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R.T.N.'),
        ),
    ]
