# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0168_employee_rtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='metodo_pago',
            field=models.NullBooleanField(verbose_name='Metodo de Pago'),
        ),
    ]
