# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0170_auto_20190701_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoingreso',
            name='orden',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden'),
        ),
    ]
