# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0171_tipoingreso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoContrato', verbose_name='Tipo Contrato'),
        ),
    ]
