# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0173_salariominimo_forzar_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoImpuestoSobreRenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('descripción', models.CharField(max_length=150, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor')),
                ('descripcion1', models.CharField(max_length=150, verbose_name='Descripcion 1')),
                ('valor1', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor 1')),
                ('descripcion2', models.CharField(max_length=150, verbose_name='Descripcion 2')),
                ('valor2', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor 2')),
            ],
            options={
                'verbose_name': 'EncabezadoImpuestoSobreRenta',
                'verbose_name_plural': 'EncabezadoImpuestoSobreRentas',
            },
        ),
        migrations.AddField(
            model_name='impuestosobrerenta',
            name='encabezado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.EncabezadoImpuestoSobreRenta', verbose_name='ISR'),
        ),
    ]
