# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0174_auto_20190709_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuestosobrerenta',
            name='encabezado',
        ),
    ]
