# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0175_remove_impuestosobrerenta_encabezado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncabezadoImpuestoSobreRenta',
        ),
    ]
