# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0176_delete_encabezadoimpuestosobrerenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoImpuestoSobreRenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('descripción', models.CharField(max_length=150, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor')),
                ('descripcion1', models.CharField(max_length=150, verbose_name='Descripcion 1')),
                ('valor1', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor 1')),
                ('descripcion2', models.CharField(max_length=150, verbose_name='Descripcion 2')),
                ('valor2', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valor 2')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.NullBooleanField()),
                ('empresa_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isr_enc_usermod', related_query_name='isr_enc_usermod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EncabezadoImpuestoSobreRenta',
                'verbose_name_plural': 'EncabezadoImpuestoSobreRentas',
            },
        ),
    ]
