# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0177_encabezadoimpuestosobrerenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuestosobrerenta',
            name='encabezado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.EncabezadoImpuestoSobreRenta', verbose_name='ISR'),
        ),
    ]
