# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0178_impuestosobrerenta_encabezado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadoimpuestosobrerenta',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vigencia'),
        ),
    ]
