# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0179_encabezadoimpuestosobrerenta_fecha_vigencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encabezadoimpuestosobrerenta',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
