# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0180_auto_20190709_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezadoimpuestosobrerenta',
            name='descripcion1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion 1'),
        ),
        migrations.AlterField(
            model_name='encabezadoimpuestosobrerenta',
            name='descripcion2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion 2'),
        ),
        migrations.AlterField(
            model_name='encabezadoimpuestosobrerenta',
            name='valor1',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor 1'),
        ),
        migrations.AlterField(
            model_name='encabezadoimpuestosobrerenta',
            name='valor2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor 2'),
        ),
    ]
