# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0181_auto_20190709_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezadoimpuestosobrerenta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='encabezadoimpuestosobrerenta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor'),
        ),
    ]
