# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0182_auto_20190715_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encabezadoimpuestosobrerenta',
            name='valor',
        ),
    ]
