# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0183_remove_encabezadoimpuestosobrerenta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadoimpuestosobrerenta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor'),
        ),
    ]
