# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0186_clasificadeduccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planilladetalleingresos',
            options={'verbose_name': 'Planilla Detalle Ingresos', 'verbose_name_plural': 'Planilla Detalle Ingresos'},
        ),
        migrations.AddField(
            model_name='planilladetallededucciones',
            name='tipo_deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoDeduccion', verbose_name='Tipo Deduccion'),
        ),
        migrations.AddField(
            model_name='planilladetalleingresos',
            name='tipo_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoIngreso', verbose_name='Tipo Ingreso'),
        ),
        migrations.AlterField(
            model_name='clasificadeduccion',
            name='tipo_deduccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.TipoDeduccion', verbose_name='Tipo Deduccion'),
        ),
    ]
