# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0187_auto_20190806_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadeduccion',
            name='orden',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='clasificadeduccion',
            name='grupo',
            field=models.CharField(choices=[('IHSS', 'IHSS'), ('IMV', 'IMPUESTO VECINAL'), ('ISR', 'ISR'), ('RAP', 'RAP'), ('OTRAS_DEDUCCIONES', 'OTRAS DEDUCCIONES')], max_length=20, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='clasificapercepcion',
            name='grupo',
            field=models.CharField(choices=[('BONO', 'BONOS'), ('OTROS_INGRESOS', 'OTROS INGRESOS')], max_length=20, verbose_name='Grupo'),
        ),
    ]
