# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0188_auto_20190812_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoingreso',
            name='grupo',
            field=models.CharField(blank=True, choices=[('BONOS', 'BONOS'), ('OTROS_INGRESOS', 'OTROS INGRESOS')], max_length=20, null=True, verbose_name='Grupo'),
        ),
    ]
