# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0190_tipodeduccion_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificadeduccion',
            name='empresa_reg',
        ),
        migrations.RemoveField(
            model_name='clasificadeduccion',
            name='tipo_deduccion',
        ),
        migrations.RemoveField(
            model_name='clasificadeduccion',
            name='user_mod',
        ),
        migrations.RemoveField(
            model_name='clasificadeduccion',
            name='user_reg',
        ),
        migrations.RemoveField(
            model_name='clasificapercepcion',
            name='empresa_reg',
        ),
        migrations.RemoveField(
            model_name='clasificapercepcion',
            name='tipo_ingreso',
        ),
        migrations.RemoveField(
            model_name='clasificapercepcion',
            name='user_mod',
        ),
        migrations.RemoveField(
            model_name='clasificapercepcion',
            name='user_reg',
        ),
        migrations.AlterField(
            model_name='tipodeduccion',
            name='grupo',
            field=models.CharField(blank=True, choices=[('IHSS', 'IHSS'), ('IMV', 'IMPUESTO VECINAL'), ('ISR', 'ISR'), ('RAP', 'RAP'), ('Otras Deducciones', 'OTRAS DEDUCCIONES')], max_length=20, null=True, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Bonos', 'BONOS'), ('Otros Ingresos', 'OTROS INGRESOS')], max_length=20, null=True, verbose_name='Grupo'),
        ),
        migrations.DeleteModel(
            name='ClasificaDeduccion',
        ),
        migrations.DeleteModel(
            name='ClasificaPercepcion',
        ),
    ]
