# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-18 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0191_auto_20190815_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPagosDeduccionIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor')),
                ('deduccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualDetalle', verbose_name='Deduccion Individual')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla')),
            ],
            options={
                'verbose_name': 'controlpagosdeduccionindividual',
                'verbose_name_plural': 'controlpagosdeduccionindividuales',
            },
        ),
        migrations.CreateModel(
            name='DeduccionIndividualSubDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('active', models.NullBooleanField(default=True)),
                ('deducciondetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualDetalle', verbose_name='Detalle Deduccion Individual')),
                ('user_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deduccionindividualsubdetalle',
                'verbose_name_plural': 'deduccionindividualsubdetalles',
            },
        ),
    ]
