# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0192_controlpagosdeduccionindividual_deduccionindividualsubdetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlpagosdeduccionindividual',
            name='planilla',
        ),
        migrations.AddField(
            model_name='deduccionindividualsubdetalle',
            name='deduccionplanilladetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualPlanilla', verbose_name='Detalle Deduccion Planilla'),
        ),
        migrations.AlterField(
            model_name='controlpagosdeduccionindividual',
            name='deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualDetalle', verbose_name='Deduccion Individual'),
        ),
        migrations.AlterField(
            model_name='deduccionindividualsubdetalle',
            name='deducciondetalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualDetalle', verbose_name='Detalle Deduccion Individual'),
        ),
    ]
