# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0194_remove_deduccionindividualsubdetalle_deduccionplanilladetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpagosdeduccionindividual',
            name='planilla_deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.PlanillaDetalleDeducciones', verbose_name='Planilla Detalle Deducción'),
        ),
        migrations.AlterField(
            model_name='controlpagosdeduccionindividual',
            name='deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualDetalle', verbose_name='Deducción Individual'),
        ),
    ]
