# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0195_auto_20200106_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlpagosdeduccionindividual',
            name='planilla_deduccion',
        ),
    ]
