# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0196_remove_controlpagosdeduccionindividual_planilla_deduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpagosdeduccionindividual',
            name='planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla'),
        ),
    ]
