# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0197_controlpagosdeduccionindividual_planilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpagosdeduccionindividual',
            name='planilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla'),
            preserve_default=False,
        ),
    ]
