# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0198_auto_20200106_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePlanillaDetalleDeduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduccion_detalle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionIndividualDetalle', verbose_name='Deduccion Individual Planilla')),
                ('planilla_detalle_ded', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='worksheet.PlanillaDetalleDeducciones', verbose_name='Planilla Detalle Deducción')),
            ],
            options={
                'verbose_name': 'detalleplanilladetallededuccion',
                'verbose_name_plural': 'detalleplanilladetallededucciones',
            },
        ),
    ]
