# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0200_auto_20200108_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='ihss',
            field=models.BooleanField(default=False, help_text='Indica si en la planilla a registrar se deducirá IHSS', verbose_name='Deducir IHSS'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='imv',
            field=models.BooleanField(default=False, help_text='Indica si en la planilla a registrar se deducirá Impuesto Vecinal', verbose_name='Deducir IMV'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='isr',
            field=models.BooleanField(default=False, help_text='Indica si en la planilla a registrar se deducirá Impuesto Sobre Renta', verbose_name='Deducir RAP'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='rap',
            field=models.BooleanField(default=False, help_text='Indica si en la planilla a registrar se deducirá RAP', verbose_name='Deducir RAP'),
        ),
    ]
