# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-23 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0201_auto_20200115_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeduccion',
            name='grupo',
            field=models.CharField(blank=True, choices=[('IHSS', 'IHSS'), ('IMV', 'Impuesto Vecinal'), ('ISR', 'ISR'), ('RAP', 'RAP'), ('Deducciones Internas', 'Deducciones Internas'), ('Deducciones Externas', 'Deducciones Externas')], max_length=20, null=True, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Salarios', 'Salarios'), ('Bonos', 'Bonos'), ('Días Libres', 'Días Libres'), ('Otros Ingresos', 'Otros Ingresos'), ('Vacaciones', 'Vacaciones')], max_length=20, null=True, verbose_name='Grupo'),
        ),
    ]
