# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0202_auto_20200123_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodeduccion',
            name='grupo',
            field=models.CharField(blank=True, choices=[('IHSS', 'IHSS'), ('IMV', 'IMPUESTO VECINAL'), ('ISR', 'ISR'), ('RAP', 'RAP'), ('DEDUCCIONES INTERNAS', 'DEDUCCIONES INTERNAS'), ('DEDUCCIONES EXTERNAS', 'DEDUCCIONES EXTERNAS')], max_length=20, null=True, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='grupo',
            field=models.CharField(blank=True, choices=[('SALARIOS', 'SALARIOS'), ('BONOS', 'BONOS'), ('DÍAS LIBRES', 'DÍAS LIBRES'), ('OTROS INGRESOS', 'OTROS INGRESOS'), ('VACACIONES', 'VACACIONES')], max_length=20, null=True, verbose_name='Grupo'),
        ),
    ]
