# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0203_auto_20200124_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduccionesUnicasArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=None, verbose_name='Archivo deducciones')),
                ('deduccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionGeneral', verbose_name='Deducción única')),
                ('planila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla')),
            ],
        ),
    ]
