# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-12 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0205_auto_20200206_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduccionEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Monto')),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DeduccionEmpleado',
                'verbose_name_plural': 'DeduccionEmpleados',
            },
        ),
        migrations.CreateModel(
            name='DeduccionesEmpleadoArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=None, verbose_name='Archivo deducciones')),
            ],
        ),
        migrations.CreateModel(
            name='DeduccionTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduccion_tipo', models.CharField(max_length=50, verbose_name='Deducción Tipo')),
                ('es_legal', models.BooleanField(verbose_name='Es legal')),
                ('es_externa', models.BooleanField(verbose_name='Es externa')),
                ('indice_relevancia', models.IntegerField(verbose_name='Indice relevancia')),
            ],
            options={
                'verbose_name': 'deducciontipo',
                'verbose_name_plural': 'deducciontipos',
            },
        ),
        migrations.AddField(
            model_name='deduccionempleado',
            name='deduccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionTipo', verbose_name='Tipo Deduccion'),
        ),
        migrations.AddField(
            model_name='deduccionempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='deduccionempleado',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dedemp_usermod', related_query_name='dedemp_usermod', to=settings.AUTH_USER_MODEL),
        ),
    ]
