# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0207_deducciontipo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduccionempleado',
            name='planilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla'),
            preserve_default=False,
        ),
    ]
