# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-19 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0208_deduccionempleado_planilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduccionempleado',
            old_name='date_mod',
            new_name='date_reg',
        ),
        migrations.RemoveField(
            model_name='deduccionempleado',
            name='user_mod',
        ),
        migrations.AddField(
            model_name='deduccionempleado',
            name='user_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dedemp_userreg', related_query_name='dedemp_usermod', to=settings.AUTH_USER_MODEL),
        ),
    ]
