# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-22 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0209_auto_20200819_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduccionempleado',
            name='date_mod',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deduccionempleado',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dedemp_usermod', related_query_name='dedemp_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='date_reg',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='user_reg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='dedemp_userreg', related_query_name='dedemp_userreg', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
