# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-08-28 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0211_deduccionempleado_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Monto')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('date_mod', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'ingresoempleado',
                'verbose_name_plural': 'ingresoempleados',
            },
        ),
        migrations.CreateModel(
            name='IngresoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_tipo', models.CharField(max_length=150, verbose_name='Tipo de ingreso')),
                ('indice_relevancia', models.IntegerField(verbose_name='Indice relevancia')),
                ('active', models.BooleanField(verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'ingresotipo',
                'verbose_name_plural': 'ingresotipos',
            },
        ),
        migrations.AddField(
            model_name='ingresoempleado',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.IngresoTipo', verbose_name='Tipo Deduccion'),
        ),
        migrations.AddField(
            model_name='ingresoempleado',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheet.Planilla', verbose_name='Planilla'),
        ),
        migrations.AddField(
            model_name='ingresoempleado',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devemp_usermod', related_query_name='devemp_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingresoempleado',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devemp_userreg', related_query_name='devemp_userreg', to=settings.AUTH_USER_MODEL),
        ),
    ]
