# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0214_auto_20200903_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladetallededucciones',
            name='tipo_deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionTipo', verbose_name='Tipo Deduccion'),
        ),
        migrations.AddField(
            model_name='planilladetalleingresos',
            name='tipo_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.IngresoTipo', verbose_name='Tipo Ingreso'),
        ),
    ]
