# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0215_auto_20200903_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='deducciontipo',
            name='visible',
            field=models.BooleanField(default=1, verbose_name='Visible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresotipo',
            name='visible',
            field=models.BooleanField(default=1, verbose_name='Visible'),
            preserve_default=False,
        ),
    ]
