# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-09-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0219_remove_contrato_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='numero',
            field=models.CharField(default=1, max_length=250, verbose_name='Numero de contrato'),
            preserve_default=False,
        ),
    ]
