# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-01 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0220_contrato_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduccionindividualsubdetalle',
            name='deducciondetalle',
        ),
    ]
