# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0221_remove_deduccionindividualsubdetalle_deducciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduccionindividualsubdetalle',
            name='deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.DeduccionEmpleado', verbose_name='Detalle Deduccion de Empleado'),
        ),
    ]
