# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0223_deduccionempleado_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduccionindividualsubdetalle',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
