# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-19 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0225_planilladetallededucciones_deduccion_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanilladetallededuccion',
            name='deduccion_detalle',
        ),
    ]
