# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-10-20 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0226_remove_detalleplanilladetallededuccion_deduccion_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleplanilladetallededuccion',
            name='planilla_detalle_ded',
        ),
        migrations.DeleteModel(
            name='DetallePlanillaDetalleDeduccion',
        ),
    ]
