# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0227_auto_20201020_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='ihss',
        ),
        migrations.AddField(
            model_name='planilla',
            name='especial',
            field=models.BooleanField(default=True, help_text='Planilla especial', verbose_name='Planilla especial'),
            preserve_default=False,
        ),
    ]
