# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0229_auto_20201026_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cuenta_contable',
            field=models.CharField(default='', max_length=150, verbose_name='Cuenta contable'),
        ),
        migrations.AlterField(
            model_name='department',
            name='empresa_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dep_empreg', related_query_name='dep_empreg', to='worksheet.Empresa'),
        ),
    ]
