# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0230_auto_20210430_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladetalle',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worksheet.Department', verbose_name='Departamento'),
        ),
    ]
