# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-10 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0231_planilladetalle_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContableAsignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_contable', models.CharField(max_length=150, verbose_name='Cuenta contable')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('date_mod', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento', to='worksheet.Department', verbose_name='Departamento')),
                ('tipo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoingreso', to='worksheet.TipoIngreso', verbose_name='Tipo Ingreso')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_mod', related_query_name='user_mod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reg', related_query_name='user_reg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuentacontableasignacion',
                'verbose_name_plural': 'cuentacontableasignaciones',
            },
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='date_mod',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='deduccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.DeduccionTipo', verbose_name='Tipo Deduccion'),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheet.Planilla', verbose_name='Planilla'),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='user_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dedemp_usermod', related_query_name='dedemp_usermod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deduccionempleado',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dedemp_userreg', related_query_name='dedemp_userreg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='deduccion_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheet.DeduccionEmpleado', verbose_name='Deduccion empleado'),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='empresa_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Empresa'),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Planilla', verbose_name='Planilla'),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='sucursal_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.Branch'),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='tipo_deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='worksheet.DeduccionTipo', verbose_name='Tipo Deduccion'),
        ),
        migrations.AlterField(
            model_name='planilladetallededucciones',
            name='user_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
