# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0232_auto_20210610_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontableasignacion',
            name='tipo_ingreso',
        ),
    ]
