# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheet', '0233_remove_cuentacontableasignacion_tipo_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontableasignacion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cuentacontableasignacion',
            name='user_mod',
        ),
        migrations.RemoveField(
            model_name='cuentacontableasignacion',
            name='user_reg',
        ),
        migrations.DeleteModel(
            name='CuentaContableAsignacion',
        ),
    ]
