# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksheet', '0234_auto_20210615_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContableAsignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_contable', models.CharField(max_length=150, verbose_name='Cuenta contable')),
                ('date_reg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('date_mod', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamento', to='worksheet.Department', verbose_name='Departamento')),
                ('tipo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoingreso', to='worksheet.IngresoTipo', verbose_name='Tipo Ingreso')),
                ('user_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_mod', related_query_name='user_mod', to=settings.AUTH_USER_MODEL)),
                ('user_reg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reg', related_query_name='user_reg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuentacontableasignacion',
                'verbose_name_plural': 'cuentacontableasignaciones',
            },
        ),
    ]
